### PR TITLE
Header files readjustment

### PR DESCRIPTION
**Pull request by CloudyPadmal**
**Changes made**
- Included `p24EP256GP204.h` and `libpic30.h` in the common header instead of calling them separately.
- Replaced unsigned data types with specific types. This was giving errors previously because of header issues. Fixed it here!

### CODE REVIEW

**Comment by sabirma** [comment]
It doesn't seem to matter if p24EP256GP204.h is included or not, as long as the processor type is configured correctly in the IDE

**Comment by CloudyPadmal** [comment]
Hello @sabirma ! If I don't include the header it gives errors saying PIC related variables are undeclared!
Error log

**Comment by CloudyPadmal** [comment]
Guys it would be really great if you can have a look at the code and see if they're okay! :)

**Comment by CloudyPadmal** [comment]
Thanks a lot for the review @jithinbp ! :) Every time MPLab is opened, that file gets updated. I will add that file to `.gitignore`! :+1:

**Comment by CloudyPadmal** [comment]
Hello @viveksb007 , @asitava1998 , @akarshan96 ! Can you take a look at the changes made during a spare time after android work? :) I need one more review to merge this PR! Thanks alot! :D

**Pull request merged**
